---
title: "Initial Models"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages}
library(tidyverse)
library(ggplot2)
library(caret)
library(caretEnsemble)
library(knitr)
library(broom)
library(patchwork)
```

```{r}
load("PrimaryData (1).RData")
daygenre <- read.csv("DayAndGenre.csv")
daygenre <- daygenre %>%
  mutate(Date = as.character(Date),
        Artist = as.character(Artists))
localacts <- read.csv("LocalActs.csv")
localacts <- localacts %>%
  mutate(Date = as.character(Date),
         Artist = as.character(Artist),
         Ref = Reference..)
```

```{r}
y <- y %>%
  separate(Date, sep="/", into = c("month", "day", "year"))
yyy <- y %>%
  mutate(new_year = str_sub(year, 3, -1))
yyy$Date <- paste0(yyy$month, "/", yyy$day, "/", yyy$new_year)
```

```{r}
full1 <- inner_join(yyy, localacts, by = c("Date", "Artist"))
full <- inner_join(full1, daygenre)
```

# Exploratory Data Analysis

```{r}
full <- full %>%
  mutate(Returning.Act = as.factor(case_when(Returning.Act == "x" ~ 1,
                               Returning.Act == "" ~ 0)),
         SPMostPlays.lt1000 = as.factor(SPMostPlays.lt1000),
         FBFansNC.lt1000 = as.factor(FBFansNC.lt1000),
         FBFans50Mi.lt1000 = as.factor(FBFans50Mi.lt1000),
         Seated = as.factor(Seated),
         SpecialTx = as.factor(SpecialTx),
         year = as.factor(year),
         month = as.factor(month),
         JointEvent = as.factor(JointEvent))

colSums(is.na(full))
```

```{r}

p0 <- ggplot(data = full, aes(x = Seated)) +
  geom_bar()

p1 <- ggplot(data = full, aes(x = month)) +
  geom_bar()

p2 <- ggplot(data = full, aes(x = year)) +
  geom_bar()

p3 <- ggplot(data = full, aes(x = SpecialTx)) +
  geom_bar()

p4 <- ggplot(data = full, aes(x = FBFans50Mi.lt1000)) +
  geom_bar()

p5 <- ggplot(data = full, aes(x = FBFansNC.lt1000)) +
  geom_bar()

p6 <- ggplot(data = full, aes(x = PSAvgTix)) +
  geom_histogram()

p7 <- ggplot(data = full, aes(x = PSAvgGross)) +
  geom_histogram()

p8 <- ggplot(data = full, aes(x = FBLikes)) +
  geom_histogram()

p9 <- ggplot(data = full, aes(x = Twitter)) +
  geom_histogram()

p10 <- ggplot(data = full, aes(x = SPFollowers)) +
  geom_histogram()

p11 <- ggplot(data = full, aes(x = SPMonthListen)) +
  geom_histogram()

p12 <- ggplot(data = full, aes(x = SPMostPlays.lt1000)) +
  geom_bar()

p13 <- ggplot(data = full, aes(x = IGFollowers)) +
  geom_histogram()

p14 <- ggplot(data = full, aes(x = SKFollowers)) +
  geom_histogram()

p15 <- ggplot(data = full, aes(x = BandsinTown)) +
  geom_histogram()

p16 <- ggplot(data = full, aes(x = Bands60Mi)) +
  geom_histogram()

p17 <- ggplot(data = full, aes(x = YTSubscribers)) +
  geom_histogram()

p18 <- ggplot(data = full, aes(x = Staff)) +
  geom_bar()

p18 <- ggplot(data = full, aes(x = JointEvent)) +
  geom_bar()

p19 <- ggplot(data = full, aes(x = Showtime)) +
  geom_bar()

p20 <- ggplot(data = full, aes(x = Day)) +
  geom_bar()

p21 <- ggplot(data = full, aes(x = Genre)) +
  geom_bar()

p22 <- ggplot(data = full, aes(x = Touring.Local)) +
  geom_bar()

p23 <- ggplot(data = full, aes(x = Returning.Act)) +
  geom_bar()

p0 + p1 + p2 + p3 + p4 + p5
p6 + p7 + p8 + p9 + p10 + p11
p12 + p13 + p14 + p15 + p16 + p17
p18 + p19 + p20 + p21 + p22 + p23


```

```{r log-graphs}

p6 <- ggplot(data = full, aes(x = log(PSAvgTix))) +
  geom_histogram()

p7 <- ggplot(data = full, aes(x = log(PSAvgGross))) +
  geom_histogram()

p8 <- ggplot(data = full, aes(x = log(FBLikes))) +
  geom_histogram()

p9 <- ggplot(data = full, aes(x = log(Twitter))) +
  geom_histogram()

p10 <- ggplot(data = full, aes(x = log(SPFollowers))) +
  geom_histogram()

p11 <- ggplot(data = full, aes(x = log(SPMonthListen))) +
  geom_histogram()

p13 <- ggplot(data = full, aes(x = log(IGFollowers))) +
  geom_histogram()

p14 <- ggplot(data = full, aes(x = log(SKFollowers))) +
  geom_histogram()

p15 <- ggplot(data = full, aes(x = log(BandsinTown))) +
  geom_histogram()

p16 <- ggplot(data = full, aes(x = log(Bands60Mi))) +
  geom_histogram()

p17 <- ggplot(data = full, aes(x = log(YTSubscribers))) +
  geom_histogram()

p6 + p7 + p8 + p9 
p10 + p11 + p13 + p14 
p15 + p16 + p17
```

```{r transform}
full <- full %>%
  mutate(logPSAvgTix = log(PSAvgTix),
         logPSAvgGross = log(PSAvgGross),
         logFBLikes = log(FBLikes),
         logTwitter = log(Twitter),
         logSPFollowers = log(SPFollowers),
         logSPMonthListen = log(SPMonthListen),
         logIGFollowers = log(IGFollowers),
         logSKFollowers = log(SKFollowers),
         logBandsinTown = log(BandsinTown),
         #logBands60Mi = log(Bands60Mi),
         logYTSubscribers = log(YTSubscribers)
         )

seated <- full %>%
  filter(Seated == "Yes") %>%
  filter(Group != "Test")

standing <- full %>%
  filter(Seated == "No") %>%
  filter(Group != "Test")

dropped <-select(full,-c("Ref.x", "day", "Artist", "TxPrice", "FBAttend", "FBInterest", "FBInvites", "FBFans50Mi", "FBFansNC", "SPMostPlays", "recordID", "new_year", "Date", "Reference..", "Ref.y", "Artists", "Bands60Mi", "PSAvgTix", "PSAvgGross", "FBLikes", "Twitter", "SPFollowers", "SPMonthListen", "IGFollowers", "SKFollowers", "BandsinTown", "YTSubscribers"))

notest <- dropped %>%
  filter(Group != "Test")
```

```{r missing-data}
library(mice)
mice_mod <- mice(dropped, method='rf')
mice_full <- complete(mice_mod)
mice_complete <- mice_full %>%
  filter(Group != "Test")

colSums(is.na(mice_complete))
```

```{r model-selection}
full_model <- lm(Attend ~ . -Group, data=mice_complete)
tidy(full_model)
```

```{r aic-model-selection}
model_selected <- step(full_model, direction = "backward")
tidy(model_selected)
```

```{r vif}
library(rms)
tidy(vif(model_selected))
```

```{r interactions}
model_int <- lm(Attend ~ (Capacity + FBFansNC.lt1000 + Touring.Local + Day + Returning.Act + logPSAvgTix + logPSAvgGross + logFBLikes + logTwitter + logSPFollowers + logSPMonthListen)*Capacity, data = mice_complete)
tidy(model_int)
anova(model_selected, model_int, test = "Chisq")
```

```{r prediction}

test <- mice_full %>%
  filter(Group == "Test")

as.integer(predict(model_selected, test))
                       
estimate_simp <- test %>%
  mutate(predicted = as.integer(predict(model_selected, test)))
```

```{r cross-fold}
RMSE = function(m, o){
  sqrt(mean((m - o)^2))
}
```



## Random Forest

```{r convert}
#need to convert all to numeric types for random forest
for(i in 1:ncol(mice_complete)){
  if(typeof(mice_complete[[i]]) == 'character'){
    mice_complete[[i]] <- as.factor(mice_complete[[i]])
  }
}
```

```{r random-forest-starting}
library(randomForest)
set.seed(100)
train <- sample(nrow(mice_complete), 0.7*nrow(mice_complete), replace = FALSE)
TrainSet <- mice_complete[train,]
ValidSet <- mice_complete[-train,]
```

```{r create-random-forest}
forest_model <- randomForest(Attend ~., data = TrainSet, importance = TRUE)
```

```{r}
# Predicting on train set
predTrain <- predict(forest_model, test, type = "class")
```

```{r add-predictions}
load("testPred.RData")

estimate <- test %>%
  mutate(predicted_simp = as.integer(predict(model_selected, test)),
         predicted_comp = as.integer(predict(forest_model, test, type = "class")))

all <- estimate %>%
  mutate(PredAttend = predicted_comp,
         PredAttend.Basic = predicted_simp)

testPredF <- all %>%
  select("recordID", "PredAttend", "PredAttend.Basic")

```

```{r}

save(testPredF, file = "testPredF.RData") 

```

